[package]
name = "ifconfig-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-files = "0.6.6"
actix-http = "3.10.0"
actix-web = "4.9.0"
buildid = "1.0.3"
clap = { version = "4.5.32", features = ["derive"] }
hex = "0.4.3"
maud = "0.27.0"
serde_json = "1.0.140"
